### ISSUE TITLE
KeyError: 'com.apple.FinderInfo' when running makeotfexe on Mac OSX 10.10.5

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/nototools#113]
makeotf [Note] Running makeotfexe with commands:
   cd "/Users/marekj/src/noto-source"
   makeotfexe "-f" "tmp1.ttf.tmp" "-o" "tmp2.ttf.temp_cff" -ff "tmp.fea" -ga -gf "tmp1.ttf.temp.GOADB" -shw
Fixing output font 'post' table...
makeotf [Error] Failed to extract source TTF font post table with 'ttx' tool. Report follows.
Traceback (most recent call last):
  File "/usr/local/bin/ttx", line 9, in <module>
    load_entry_point('fonttools==3.0', 'console_scripts', 'ttx')()
  File "/Library/Python/2.7/site-packages/fonttools-3.0-py2.7.egg/fontTools/ttx.py", line 352, in main
    jobs, options = parseOptions(args)
  File "/Library/Python/2.7/site-packages/fonttools-3.0-py2.7.egg/fontTools/ttx.py", line 306, in parseOptions
    tp = guessFileType(input)
  File "/Library/Python/2.7/site-packages/fonttools-3.0-py2.7.egg/fontTools/ttx.py", line 268, in guessFileType
    cr, tp = getMacCreatorAndType(fileName)
  File "/Library/Python/2.7/site-packages/fonttools-3.0-py2.7.egg/fontTools/misc/macCreatorType.py", line 23, in getMacCreatorAndType
    finderInfo = xattr.getxattr(path, 'com.apple.FinderInfo')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/xattr/__init__.py", line 186, in getxattr
    return xattr(f).get(attr, options=symlink and XATTR_NOFOLLOW or 0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/xattr/__init__.py", line 84, in get
    return self._get(name, 0, 0, options | self.options)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/xattr/__init__.py", line 28, in _func
    return func(first, *args)
KeyError: 'com.apple.FinderInfo'

**Comment by anthrotype** [comment]
Fixed in https://github.com/behdad/fonttools/pull/406

**Comment by marekjez86** [comment]
@anthrotype verified fixed. Thanks you
