### ISSUE TITLE
breaks with a narrow python build

### ISSUE THREAD

**Issue by gilbahat** [googlei18n/nototools#135]
$ python add_svg_glyphs.py
Traceback (most recent call last):
  File "add_svg_glyphs.py", line 37, in <module>
    import add_emoji_gsub
  File "/Users/gilbahat/fonts/noto-fonts-master/add_emoji_gsub.py", line 28, in <module>
    from nototools import font_data
  File "/Users/gilbahat/fonts/noto-fonts-master/nototools/font_data.py", line 21, in <module>
    from nototools import opentype_data
  File "/Users/gilbahat/fonts/noto-fonts-master/nototools/opentype_data.py", line 330, in <module>
    _set_ompl()
  File "/Users/gilbahat/fonts/noto-fonts-master/nototools/opentype_data.py", line 33, in _set_ompl
    unicode_data.load_data()
  File "/Users/gilbahat/fonts/noto-fonts-master/nototools/unicode_data.py", line 75, in load_data
    _load_unicode_data_txt()
  File "/Users/gilbahat/fonts/noto-fonts-master/nototools/unicode_data.py", line 457, in _load_unicode_data_txt
    decomposition = [unichr(int(char, 16)) for char in decomposition]
ValueError: unichr() arg not in range(0x10000) (narrow Python build)

a narrow python build will be a common situation... and specifically there's this: https://github.com/Homebrew/homebrew/pull/32368 :(

**Comment by anthrotype** [comment]
You could try to use `from fontTools.misc.py23 import unichr`.

https://github.com/behdad/fonttools/blob/master/Lib/fontTools/misc/py23.py#L20

**Comment by gilbahat** [comment]
still no dice. build also breaks for wide python:
(wide)
Parsing 'GSUB' table...
Traceback (most recent call last):
  File "/usr/local/bin/ttx", line 9, in <module>
    load_entry_point('fonttools==3.0', 'console_scripts', 'ttx')()
  File "/usr/local/lib/python2.7/site-packages/fonttools-3.0-py2.7.egg/fontTools/ttx.py", line 357, in main
    process(jobs, options)
  File "/usr/local/lib/python2.7/site-packages/fonttools-3.0-py2.7.egg/fontTools/ttx.py", line 336, in process
    action(input, output, options)
  File "/usr/local/lib/python2.7/site-packages/fonttools-3.0-py2.7.egg/fontTools/ttx.py", line 255, in ttCompile
    ttf.save(output)
  File "/usr/local/lib/python2.7/site-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/__init__.py", line 202, in save
    self._writeTable(tag, writer, done)
  File "/usr/local/lib/python2.7/site-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/__init__.py", line 631, in _writeTable
    tabledata = self.getTableData(tag)
  File "/usr/local/lib/python2.7/site-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/__init__.py", line 644, in getTableData
    return self.tables[tag].compile(self)
  File "/usr/local/lib/python2.7/site-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/_c_m_a_p.py", line 82, in compile
    chunk = table.compile(ttFont)
  File "/usr/local/lib/python2.7/site-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/_c_m_a_p.py", line 984, in compile
    raise KeyError(name)
KeyError: u'uDEAB'
make: *** [NotoColorEmoji.tmpl.ttf] Error 1
rm NotoColorEmoji.tmpl.ttx

(narrow)
Parsing 'GSUB' table...
Traceback (most recent call last):
  File "/usr/local/bin/ttx", line 9, in <module>
    load_entry_point('fonttools==3.0', 'console_scripts', 'ttx')()
  File "/usr/local/lib/python2.7/site-packages/fonttools-3.0-py2.7.egg/fontTools/ttx.py", line 357, in main
    process(jobs, options)
  File "/usr/local/lib/python2.7/site-packages/fonttools-3.0-py2.7.egg/fontTools/ttx.py", line 336, in process
    action(input, output, options)
  File "/usr/local/lib/python2.7/site-packages/fonttools-3.0-py2.7.egg/fontTools/ttx.py", line 255, in ttCompile
    ttf.save(output)
  File "/usr/local/lib/python2.7/site-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/__init__.py", line 202, in save
    self._writeTable(tag, writer, done)
  File "/usr/local/lib/python2.7/site-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/__init__.py", line 631, in _writeTable
    tabledata = self.getTableData(tag)
  File "/usr/local/lib/python2.7/site-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/__init__.py", line 644, in getTableData
    return self.tables[tag].compile(self)
  File "/usr/local/lib/python2.7/site-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/_c_m_a_p.py", line 82, in compile
    chunk = table.compile(ttFont)
  File "/usr/local/lib/python2.7/site-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/_c_m_a_p.py", line 984, in compile
    raise KeyError(name)
KeyError: u'uDEAB'
make: *** [NotoColorEmoji.tmpl.ttf] Error 1
rm NotoColorEmoji.tmpl.ttx
