### ISSUE TITLE
noto_lint.py: "ValueError: no such name" when processing NotoSansDisplay-Regular.otf

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/nototools#175]
I built the pipeline in the evening of 16/Feb/2016.
I ran the lint on the output of the pipeline in the master_otf directory created by the pipeline.
This bug could be a pipeline otf file creation bug (please forward) or a noto_lint.py issue.

The input file for the pipeline is attached 
[NotoSansDisplay-RomanMM.glyphs.zip](https://github.com/googlei18n/nototools/files/134258/NotoSansDisplay-RomanMM.glyphs.zip)

The OTF file will be attached later when I am able to retrieve it (not able to scp it from home to my linux machine for security reasons)

======== NotoSansDisplay-Regular.otf ============
unknown hint status for , defaulting to unhinted
Traceback (most recent call last):
  File "/usr/local/bin/noto_lint.py", line 4, in <module>
    **import**('pkg_resources').run_script('nototools==0.0.1', 'noto_lint.py')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 726, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 1651, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/nototools-0.0.1-py2.7.egg/EGG-INFO/scripts/noto_lint.py", line 1997, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/nototools-0.0.1-py2.7.egg/EGG-INFO/scripts/noto_lint.py", line 1964, in main
    arguments.phase)
  File "/usr/local/lib/python2.7/dist-packages/nototools-0.0.1-py2.7.egg/EGG-INFO/scripts/noto_lint.py", line 1802, in check_font
    check_gdef_table(cmap)
  File "/usr/local/lib/python2.7/dist-packages/nototools-0.0.1-py2.7.egg/EGG-INFO/scripts/noto_lint.py", line 1248, in check_gdef_table
    unicode_data.name(code),
  File "/usr/local/lib/python2.7/dist-packages/nototools-0.0.1-py2.7.egg/nototools/unicode_data.py", line 107, in name
    raise val_error
ValueError: no such name

**Comment by marekjez86** [comment]
The OTF file that was input to noto_lint.py
[NotoSansDisplay-Regular.otf.zip](https://github.com/googlei18n/nototools/files/134618/NotoSansDisplay-Regular.otf.zip)

**Comment by behdad** [comment]
@dougfelt can you make `noto_lint` at least print what name is not found?

**Comment by behdad** [comment]
@jungshik can you modify `noto_lint` and see what's missing, then debug it to the root cause?

**Comment by dougfelt** [comment]
I just built the zip that Marek provided, and ran noto_lint on all the NotoSansDisplay*.otf fonts.  There was no crash.  I guess I can try refreshing the toolchain and rebuilding...

**Comment by marekjez86** [comment]
I updated the pipeline (although it looks that it hasn't changed for several days).
I'm running it right now on all of my inputs.
Then i'll run noto-lint.py and keep you all informed.

**Comment by dougfelt** [comment]
I cannot reproduce it.  I updated the tools, ran noto_lint from master, and
it succeeds.

**Comment by marekjez86** [comment]
everything is cool now (not able to reproduce)
