### ISSUE TITLE
notodiff: handling of fonts within TTC is desired

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/nototools#253]
$ notodiff -t rendered --render-path renderings --before /Library/Fonts/Phosphate.ttc --after /Library/Fonts/Phosphate.ttc
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/notodiff", line 9, in <module>
    load_entry_point('nototools==0.0.1', 'console_scripts', 'notodiff')()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nototools-0.0.1-py2.7.egg/nototools/notodiff.py", line 131, in main
    args.render_path)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nototools-0.0.1-py2.7.egg/nototools/notodiff.py", line 43, in _shape
    path_a, path_b, stats, ratio_diffs=True)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nototools-0.0.1-py2.7.egg/nototools/shape_diff.py", line 45, in __init__
    self.font_a = TTFont(self.path_a)
  File "/Users/marekj/Library/Python/2.7/lib/python/site-packages/FontTools/fontTools/ttLib/__init__.py", line 180, in __init__
    self.reader = sfnt.SFNTReader(file, checkChecksums, fontNumber=fontNumber)
  File "/Users/marekj/Library/Python/2.7/lib/python/site-packages/FontTools/fontTools/ttLib/sfnt.py", line 62, in __init__
    raise ttLib.TTLibError("specify a font number between 0 and %d (inclusive)" % (self.numFonts - 1))
fontTools.ttLib.TTLibError: specify a font number between 0 and 1 (inclusive)

**Comment by marekjez86** [comment]
Note that I also filed related googlei18n/fontreport#7 and https://github.com/googlei18n/fontdiff/issues/6 ; if there's something that needs to be done here please coordinate with the https://github.com/googlei18n/fontreport and https://github.com/googlei18n/fontdiff component owners so the tools look like they have a common interface.
