### ISSUE TITLE
notodiff: AssertionError while processing NotoSansArabic-Black.ttf

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/nototools#261]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/notodiff", line 9, in <module>
    load_entry_point('nototools==0.0.1', 'console_scripts', 'notodiff')()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nototools-0.0.1-py2.7.egg/nototools/notodiff.py", line 131, in main
    args.render_path)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nototools-0.0.1-py2.7.egg/nototools/notodiff.py", line 48, in _shape
    diff_finder.find_rendered_diffs(render_path=render_path)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nototools-0.0.1-py2.7.egg/nototools/shape_diff.py", line 115, in find_rendered_diffs
    assert text_a.strip() == text_b.strip()
AssertionError

[NotoSansArabic-Black.ttf.zip](https://github.com/googlei18n/nototools/files/363667/NotoSansArabic-Black.ttf.zip)

**Comment by jamesgk** [comment]
There's only one font in the attached .zip

**Comment by jamesgk** [comment]
I think this is fixed, but I was never able to reproduce the issue. Can you confirm Marek?

**Comment by jamesgk** [comment]
Assuming fixed.

**Comment by marekjez86** [comment]
verified fixed. thank you
