### ISSUE TITLE
notodiff: TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/nototools#263]
NotoSerifDisplay-Thin.ttf
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/notodiff", line 9, in <module>
    load_entry_point('nototools==0.0.1', 'console_scripts', 'notodiff')()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nototools-0.0.1-py2.7.egg/nototools/notodiff.py", line 131, in main
    args.render_path)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nototools-0.0.1-py2.7.egg/nototools/notodiff.py", line 48, in _shape
    diff_finder.find_rendered_diffs(render_path=render_path)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nototools-0.0.1-py2.7.egg/nototools/shape_diff.py", line 102, in find_rendered_diffs
    name, pad=(self.glyph_set_a[name].width == 0))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nototools-0.0.1-py2.7.egg/nototools/hb_input.py", line 72, in input_from_name
    gsub, glyph, lookup_index, features)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nototools-0.0.1-py2.7.egg/nototools/hb_input.py", line 109, in _input_with_context
    return self._sequence_from_glyph_names(glyphs, features)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nototools-0.0.1-py2.7.egg/nototools/hb_input.py", line 119, in _sequence_from_glyph_names
    features, cur_text = self.input_from_name(glyph, features)
TypeError: 'NoneType' object is not iterable

[NotoSerifDisplay-Thin.ttf.zip](https://github.com/googlei18n/nototools/files/364068/NotoSerifDisplay-Thin.ttf.zip)

**Comment by dougfelt** [comment]
Looks like perhaps input_from_name can fall off the end and return None?
