### ISSUE TITLE
cannot merge NotoSansMyanmar-Regular.ttf with NotoSansLatin-Regular.ttf 

### ISSUE THREAD

**Issue by xiangyexiao** [googlei18n/nototools#305]
I first subsetted the basic Latin from NotoSans-Regular.ttf, then tried to merge the result (NotoSansLatin-Regular.ttf ) with NotoSansMyanmar-Regular.ttf.

These are my commands:
pyftsubset NotoSans-Regular.ttf --unicodes=U+0000-007f
pyftmerge NotoSansMyanmar-Regular.ttf NotoSansLatin-Regular.ttf 

Error message:
Traceback (most recent call last):
  File "/usr/local/bin/pyftmerge", line 9, in <module>
    load_entry_point('fonttools==3.1.2+172.gea958e7', 'console_scripts', 'pyftmerge')()
  File "/usr/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(_args, *_kwds)
  File "/usr/local/lib/python2.7/site-packages/fontTools/merge.py", line 943, in main
    font = merger.merge(args)
  File "/usr/local/lib/python2.7/site-packages/fontTools/merge.py", line 813, in merge
    table = clazz(tag).merge(self, tables)
  File "/usr/local/lib/python2.7/site-packages/fontTools/merge.py", line 516, in merge
    feature = [featureMap[v] for v in langsys.FeatureIndex if featureMap[v].FeatureTag == 'locl']
AttributeError: 'NoneType' object has no attribute 'FeatureIndex'

**Comment by xiangyexiao** [comment]
@jungshik @brawer

**Comment by jungshik** [comment]
Perhaps, just transplanting glyphs for U+0021 ~ U+007E from Noto Sans to Noto Sans Myanmar might work better. I can try it how it comes out.

**Comment by xiangyexiao** [comment]
I have moved the bug to the right place. 
https://github.com/fonttools/fonttools/issues/739

close this bug.
