### ISSUE TITLE
enhancement for notodiff rendered: NO assert height_a == height_b ?

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/nototools#323]
NotoSansArmenian-Bold

notodiff -t 'rendered' --render-path "rnd" --diff-threshold 0.02 
--before [NotoSansArmenian-Bold.ttf.zip](https://github.com/googlei18n/nototools/files/629312/NotoSansArmenian-Bold.ttf.zip)
--after [NotoSansArmenian-Bold.ttf.zip](https://github.com/googlei18n/nototools/files/629313/NotoSansArmenian-Bold.ttf.zip)

produces the stack trace which can be seen below.

I'm not sure if it is possible to avoid 'assert height_a == height_b' and finding a "common ground" for the comparisons of images, but if it's possble then it would be preferable to a traceback.

Traceback (most recent call last):
  File "/usr/local/bin/notodiff", line 9, in <module>
    load_entry_point('nototools==0.0.1', 'console_scripts', 'notodiff')()
  File "/usr/local/lib/python2.7/dist-packages/nototools-0.0.1-py2.7.egg/nototools/notodiff.py", line 151, in main
    args.font_size, args.render_path, args.diff_threshold)
  File "/usr/local/lib/python2.7/dist-packages/nototools-0.0.1-py2.7.egg/nototools/notodiff.py", line 58, in _shape
    diff_finder.find_rendered_diffs(font_size, render_path)
  File "/usr/local/lib/python2.7/dist-packages/nototools-0.0.1-py2.7.egg/nototools/shape_diff.py", line 180, in find_rendered_diffs
    assert height_a == height_b
AssertionError

**Comment by jamesgk** [comment]
Should be fixed in latest nototools
