### ISSUE TITLE
noto_lint failed: AttributeError: 'NoneType' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by xiangyexiao** [googlei18n/nototools#328]
got the following error while running python noto_lint.py ~/fonts4android/NotoSansCherokee-Regular.ttf:

unknown hint status for /Users/xiangye/fonts4android, defaulting to unhinted
notoconfig has no entry for noto_tools
---
Automatic testing for 'fonts4android,NotoSansCherokee-Regular.ttf', Version 1.900 (head fontRevision: 1.901):
E <name/full_name> The full name is 'Noto Sans Cherokee' but was expecting 'Noto Sans Cherokee Regular'
E <name/version/match_head> fontRevision in 'head' table is 1.901, while font version in 'name' table is 1.900.
E <cmap/tables/unexpected> 'cmap' has a subtable of (format=4, platform=0, encoding=3), which it shouldn't have.
notoconfig has no entry for noto_tools
Traceback (most recent call last):
  File "noto_lint.py", line 2079, in <module>
    main()
  File "noto_lint.py", line 2046, in main
    arguments.phase)
  File "noto_lint.py", line 1877, in check_font
    cmap = check_cmap_table()
  File "noto_lint.py", line 814, in check_cmap_table
    _check_needed_chars(cmap, tests.get_filter('cmap/script_required'))
  File "noto_lint.py", line 722, in _check_needed_chars
    noto_font, noto_phase, 'cmap/script_required')
  File "noto_lint.py", line 705, in _get_required_chars
    script_to_chars = _get_cmap_data_for_phase(noto_phase)
  File "noto_lint.py", line 383, in _get_cmap_data_for_phase
    _phase_3_map = _build_cmap_dict('noto_cmap_phase3.xml')
  File "noto_lint.py", line 367, in _build_cmap_dict
    path.join(tooldir, filename))
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'

**Comment by dougfelt** [comment]
This should have been fixed by other recent changes.
