### ISSUE TITLE
[notodiff] OSError: No such file or directory

### ISSUE THREAD

**Issue by zjusbo** [googlei18n/nototools#392]
It seems it is caused by lacking some dependencies. 

Steps to reproduce:
1. Update nototools, fontmake and fonttools to latest version. (I tried Mac and Linux all have the same error)
2. run command
notodiff --before NotoSansTamilUI-Regular.otf --after ~/noto-source/src/NotoSansTamil/instance_otf/NotoSansTamilUI-Regular.otf -t rendered --render-path ./

Expected result:
Generate diff images.

Actual result:
Traceback (most recent call last):
  File "/usr/local/google/home/bosong/fonttools/dev/bin/notodiff", line 11, in <module>
    load_entry_point('nototools', 'console_scripts', 'notodiff')()
  File "/usr/local/google/home/bosong/nototools/nototools/notodiff.py", line 157, in main
    args.font_size, args.render_path, args.diff_threshold)
  File "/usr/local/google/home/bosong/nototools/nototools/notodiff.py", line 58, in _shape
    diff_finder.find_rendered_diffs(font_size, render_path)
  File "/usr/local/google/home/bosong/nototools/nototools/shape_diff.py", line 158, in find_rendered_diffs
    '--features=%s' % ','.join(features), self.path_a, text]))
  File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by zjusbo** [comment]
The system does not contains libharfbuzz-bin so that it can not render images. Investigating.

**Comment by zjusbo** [comment]
In linux, sudo apt-get libharfbuzz-bin solves this problem. Closing this issue. Why is it not installed automatically when installing nototools?
