### ISSUE TITLE
noto_lint and Noto Music naming

### ISSUE THREAD

**Issue by punchcutter** [googlei18n/nototools#474]
We are prepping Noto Sans Music for delivery, but the expected names don't match what we have. Should it really be called Noto Sans Music or just Noto Music? The updates pointed to in https://github.com/googlei18n/nototools/pull/441 show where the Music naming is all coming from, but it doesn't seem quite correc. With Sans in the name noto_lint just fails with "ERROR: cannot parse". 
If we take out Sans and just have Noto Music then noto_lint fails with
```
E <name/family> The family is 'Noto Music' but was expecting 'Noto Music MUSE'
E <name/full_name> The full name is 'Noto Music Regular' but was expecting 'Noto Music MUSE Regular'
E <name/postscript_name> The postscript name is 'NotoMusic-Regular' but was expecting 'NotoMusicMUSE-Regular'
E <cmap/script_required> no char data for script MUSE in NotoMusic-Regular.otf
E <cmap/private_use> no char data for script MUSE in NotoMusic-Regular.otf
Traceback (most recent call last):
  File "/usr/local/bin/noto_lint.py", line 4, in <module>
    __import__('pkg_resources').run_script('nototools==0.0.1', 'noto_lint.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/nototools-0.0.1-py2.7.egg/EGG-INFO/scripts/noto_lint.py", line 2153, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/nototools-0.0.1-py2.7.egg/EGG-INFO/scripts/noto_lint.py", line 2119, in main
    arguments.variable)
  File "/usr/local/lib/python2.7/dist-packages/nototools-0.0.1-py2.7.egg/EGG-INFO/scripts/noto_lint.py", line 1944, in check_font
    cmap = check_cmap_table()
  File "/usr/local/lib/python2.7/dist-packages/nototools-0.0.1-py2.7.egg/EGG-INFO/scripts/noto_lint.py", line 857, in check_cmap_table
    privates_in_cmap = {char for char in cmap if is_unwanted_pua(char)}
  File "/usr/local/lib/python2.7/dist-packages/nototools-0.0.1-py2.7.egg/EGG-INFO/scripts/noto_lint.py", line 857, in <setcomp>
    privates_in_cmap = {char for char in cmap if is_unwanted_pua(char)}
  File "/usr/local/lib/python2.7/dist-packages/nototools-0.0.1-py2.7.egg/EGG-INFO/scripts/noto_lint.py", line 849, in is_unwanted_pua
    if char in needed_chars:
TypeError: argument of type 'NoneType' is not iterable

```
That's because noto_cmap_phase3.xml has MUSIC,MUSIC instead of MUSE,MUSIC. If I change that then it completes, but still complains about the naming. So, what name do we want to use here?

**Comment by punchcutter** [comment]
Yes, I changed it to MUSE,Music and it passes, but still gives the same warnings for the name table since MUSE isn't actually part of the name.

**Comment by dougfelt** [comment]
Yeah, I need to special-case that.  It will be easier to make sure everything is working if I have a font to test against., otherwise I have to create a fake.

**Comment by dougfelt** [comment]
You can try adding a line in nototools/nototools/noto_names.py after line 127:

'MUSE': None,

And that should suppress the script name.  Let me know if that works.

**Comment by dougfelt** [comment]
Please update nototools and let me know if there are any other issues.

**Comment by punchcutter** [comment]
Looks good to me now. Thanks.
