### ISSUE TITLE
Nototools installation fails on Windows 11

### ISSUE THREAD

**Issue by oomek** [googlei18n/nototools#795]
Here is the error log:
```
D:\Downloads\nototools>pip install -e .
Obtaining file:///D:/Downloads/nototools
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      c:\apps\tools\python\Lib\site-packages\setuptools\installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "D:\Downloads\nototools\setup.py", line 11, in <module>
          setup(
        File "c:\apps\tools\python\Lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "c:\apps\tools\python\Lib\site-packages\setuptools\_distutils\core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
                                       ^^^^^^^^^^^^
        File "c:\apps\tools\python\Lib\site-packages\setuptools\dist.py", line 476, in __init__
          _Distribution.__init__(
        File "c:\apps\tools\python\Lib\site-packages\setuptools\_distutils\dist.py", line 282, in __init__
          self.finalize_options()
        File "c:\apps\tools\python\Lib\site-packages\setuptools\dist.py", line 900, in finalize_options
          ep(self)
        File "c:\apps\tools\python\Lib\site-packages\setuptools\dist.py", line 920, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "d:\downloads\nototools\.eggs\setuptools_scm-7.1.0-py3.11.egg\setuptools_scm\integration.py", line 91, in version_keyword
          _assign_version(dist, config)
        File "d:\downloads\nototools\.eggs\setuptools_scm-7.1.0-py3.11.egg\setuptools_scm\integration.py", line 63, in _assign_version
          _version_missing(config)
        File "d:\downloads\nototools\.eggs\setuptools_scm-7.1.0-py3.11.egg\setuptools_scm\__init__.py", line 108, in _version_missing
          raise LookupError(
      LookupError: setuptools-scm was unable to detect version for D:\Downloads\nototools.

      Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

      For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Python 3.11.3

**Comment by HyegeunCho** [comment]
In my case, this command worked without any errors.

`pip install "git+https://github.com/notofonts/nototools.git"`
